const ActionTypes = {
    // FilterStore
    SET_FILTER_ADD_SENSOR: 'SET_FILTER_ADD_SENSOR',
    SET_FILTER_REMOVE_SENSOR: 'SET_FILTER_REMOVE_SENSOR',
    SET_FILTER_START_DATE: 'SET_FILTER_START_DATE',
    SET_FILTER_END_DATE: 'SET_FILTER_END_DATE',
    SET_FILTER_SELECTED_FIELD: 'SET_FILTER_SELECTED_FIELD',

    // SensorStore
    SENSOR_LIST_REQUEST: 'SENSOR_LIST_REQUEST',
    SENSOR_LIST_RECEIVED: 'SENSOR_LIST_RECEIVED',
    SENSOR_LIST_ERROR: 'SENSOR_LIST_ERROR'
};

export default ActionTypes;
